name: liullm
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - cudatoolkit
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib
  - scipy
  - scikit-learn
  - ipython
  - jupyter
  - tqdm
  - pyyaml>=6.0
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - tokenizers>=0.13.3
    - sentencepiece>=0.1.99
    - huggingface_hub>=0.16.4
    - accelerate>=0.20.3
    - wandb>=0.15.0
    - deepspeed>=0.9.5
    - ftfy>=6.1.0
    - evaluate>=0.4.0
    - prefect>=2.10.0
    - tensorboard>=2.14.0
    - boto3
    - pyarrow>=12.0.0
    - jsonlines
    - hydra-core>=1.3.2
    - omegaconf>=2.3.0 