name: liullm
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.1.0
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - cudatoolkit
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - scipy>=1.10.1
  - scikit-learn>=1.2.2
  - ipython
  - jupyter
  - tqdm>=4.65.0
  - pyyaml>=6.0
  - jsonlines>=3.1.0
  - notebook>=6.5.0
  - tensorboard>=2.10.0
  - sentencepiece>=0.1.97
  - pip:
    - transformers>=4.30.0
    - datasets>=2.12.0
    - tokenizers>=0.13.3
    - sentencepiece>=0.1.99
    - huggingface_hub>=0.16.4
    - accelerate>=0.20.0
    - wandb>=0.15.0
    - deepspeed>=0.9.0
    - ftfy>=6.1.1
    - evaluate>=0.4.0
    - prefect>=2.10.0
    - boto3
    - pyarrow>=12.0.0
    - hydra-core>=1.3.2
    - omegaconf>=2.3.0
    - bitsandbytes>=0.39.0
    #- flash-attn>=2.0.0
    - datatrove>=0.1.0
    - requests>=2.28.0
    - tqdm>=4.65.0
    - huggingface-hub>=0.16.4
    - peft>=0.4.0 