# Fine-tuning Configuration

# Output directory
output_dir: "outputs/finetuned"

# Training hyperparameters
training:
  # LoRA parameters
  lora:
    use_lora: true
    r: 16
    alpha: 32
    dropout: 0.05
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
  
  # Training parameters
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 2.0e-5
  weight_decay: 0.01
  warmup_ratio: 0.03
  max_grad_norm: 1.0
  
  # Optimizer and scheduler
  optimizer_type: "adamw_torch"
  lr_scheduler_type: "cosine"
  
  # Evaluation and logging
  eval_steps: 0.1  # Fraction of training steps
  save_steps: 0.2  # Fraction of training steps
  logging_steps: 10
  report_to: ["tensorboard"]
  
  # Mixed precision
  fp16: true
  bf16: false
  
  # Other
  seed: 42
  ddp_find_unused_parameters: false
  gradient_checkpointing: true
  
# Generation parameters for evaluation
generation:
  max_new_tokens: 512
  do_sample: true
  temperature: 0.7
  top_p: 0.9
  top_k: 50
  repetition_penalty: 1.1
  
# Data configuration
data:
  prompt_template: "<s>User: {instruction}\nAssistant: "  # Template for instruction prompts
  completion_template: "{response}</s>"                   # Template for instruction completions
  max_length: 2048                                        # Maximum sequence length 